sudo: required

language: cpp
services:
  - docker

before_install:
  - docker pull ubuntu:16.04
  - docker build -f Dockerfiles/Dockerfile.base -t sai:base .

jobs:
  include:
    - stage: test
      script:
      - docker build -f Dockerfiles/Dockerfile.gpu -t sai:gpu .
      - docker run sai:gpu
    - script:
      - docker build -f Dockerfiles/Dockerfile.gpu-blas -t sai:gpu-blas .
      - docker run sai:gpu-blas
    - script:
      - docker build -f Dockerfiles/Dockerfile.cpu -t sai:cpu .
      - docker run sai:cpu
    - script:
      - docker build -f Dockerfiles/Dockerfile.cpu-blas -t sai:cpu-blas .
      - docker run sai:cpu-blas
    - script:
      - docker build -f Dockerfiles/Dockerfile.tests -t sai:tests .
      - docker run sai:tests
    - script:
      - docker build -f Dockerfiles/Dockerfile.tests-blas -t sai:tests-blas .
      - docker run sai:tests-blas
    - stage: style
      before_install:
      script: find . -regex ".*\.\(cpp\|h\|hpp\)" -not -regex ".*moc_.*.cpp" -not -path "./gtest/*" -not -path "./training/*" -not -path "./src/half/*" -not -path "./src/CL/*" -not -path "./src/Eigen/*" | xargs python2 scripts/cpplint.py --filter=-build/c++11,-build/include,-build/include_order,-build/include_what_you_use,-build/namespaces,-readability/braces,-readability/casting,-readability/fn_size,-readability/namespace,-readability/todo,-runtime/explicit,-runtime/indentation_namespace,-runtime/int,-runtime/references,-whitespace/blank_line,-whitespace/braces,-whitespace/comma,-whitespace/comments,-whitespace/empty_loop_body,-whitespace/line_length,-whitespace/semicolon
